accounts/urls.py
from django.urls import path
from .views import loginPage, logoutUser, profileUser

app_name = 'users'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profileUser, name='profile')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('files.urls', namespace='files')),
    path('', include('accounts.urls', namespace='accounts')),
]

files/urls.py
from django.urls import path
from .views import upload_file_view

app_name='files'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
]

users/urls.py
from django.urls import path
from .views import loginPage, logoutUser

app_name = 'users'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    avatar = models.CharField(max_length=255, default="https://pbs.twimg.com/media/BcINeMVCIAABeWd.jpg")
    
    def __str__(self):
        return f'Username: {self.avatar}'

files/models.py
from django.db import models


class File(models.Model):
    file_name_csv = models.FileField(upload_to='files/file_csv')
    file_name_xml = models.FileField(upload_to='files/file_xml')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)
    
    def __str__(self):
        return f'file id: {self.id}'

files/forms.py
from django import forms

from .models import File


class FileModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file_name_csv', 'file_name_xml',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from .models import Account
from .decorators import allowed_user


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_admin = authenticate(
            request, username=username, password=password)

        if user_admin is not None:
            login(request, user_admin)
            return redirect('/')
        else:
            messages.info(request, 'Username or password is incorrect')
            return render(request, 'accounts/login.html', {})

    return render(request, 'accounts/login.html', {})


def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

@login_required(login_url='accounts:login')
@allowed_user(allowed_roles=['user'])
def profileUser(request, username):
    user = User.objects.get(username=username)
    avatar = Account.objects.get(user_id=user.id).avatar

    if str(request.user) != username:
        return redirect('accounts:profile', username=request.user)
    return render(
        request,
        'accounts/profile.html',
        {
            'user': user,
            'avatar': avatar
        })

files/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.db.models import Q

from .forms import FileModelForm
from .models import File

from .helper.file_parsers import parse_csv_file, parse_xml_file
from .helper.check_users import check_users

from accounts.models import Account
from accounts.decorators import admin_only


@login_required(login_url='accounts:login')
@admin_only
def upload_file_view(request):
    form = FileModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        obj = File.objects.get(activated=False)

        list_csv_users = parse_csv_file(obj.file_name_csv.path)

        list_xml_users = parse_xml_file(obj.file_name_xml.path)

        obj.activated = True
        obj.save()

        list_users = check_users(list_csv_users, list_xml_users)

        for user in list_users:
            User.objects.create_user(
                username=user['username'],
                password=user['password'],
                date_joined=user['date_joined'],
            )
            current_user = User.objects.latest('id')
            group = Group.objects.get(name='user')
            group.user_set.add(current_user)

            Account.objects.create(
                avatar=user['avatar'],
                user_id=current_user.id
            )

    accounts = [{
        'id': x.id,
        'username': x.username,
        'date_joined': x.date_joined,
        'avatar': Account.objects.get(user_id=x.id).avatar
    } for x in User.objects.filter(~Q(id=1))]

    return render(
        request,
        'accounts/upload.html',
        {
            'form': form,
            'users': accounts,
        })

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />
    <link href="{% static 'login.css' %}" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">LOGIN</h3>
          </div>
          <div class="d-flex justify-content-center form_container">
            <form method="POST" action="">
              {% csrf_token %}
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"
                    ><i class="fas fa-user"></i
                  ></span>
                </div>
                <input
                  type="text"
                  name="username"
                  placeholder="Username..."
                  class="form-control"
                />
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"
                    ><i class="fas fa-key"></i
                  ></span>
                </div>
                <input
                  type="password"
                  name="password"
                  placeholder="Password..."
                  class="form-control"
                />
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login" />
              </div>
            </form>
          </div>

          {% for message in messages %}
          <p id="messages">{{ message }}</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
  Profile 
{% endblock title %}

{% block css %}
  <link rel="stylesheet" href="{% static 'header.css' %}" />
{% endblock css %} 

{% block content %}
<div class="main">
  <h2>IDENTITY</h2>
  <div class="card">
    <div class="card-body">
      <table>
        <tbody>
          <tr>
            <td>Name: {{ user.username }}</td>
          </tr>
          <tr>
            <td>Date joined: {{ user.date_joined}}</td>
          </tr>

          <tr>
            <td><img src="{{avatar}}" width="40%" height="40%" /></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/upload.html
{% extends 'base.html' %}

{% block title %}
main page
{% endblock title %} 


{% block content %}
<form action="" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="ui button primary">Confirm</button>
</form>
{% if users %}
    {% for user in users %}
    <div class="main">
        <div class="card">
          <div class="card-body">
            <table>
              <tbody>
                <tr>
                  <td>Name: {{ user.username }}</td>
                </tr>
                <tr>
                  <td>Date joined: {{ user.date_joined}}</td>
                </tr>
      
                <tr>
                  <td><img src="{{user.avatar}}" width="40%" height="40%" /></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    {% endfor %}
{% endif %}
{% endblock content %} 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="{% static 'header.css' %}">
  </head>
  <body>
      <div class="navbar-top">
        <ul>
            <li>
                <a href="{% url 'users:logout' %}">
                    <i class="fa fa-sign-out-alt fa-2x"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="ui container">{% block content %} {% endblock content %}</div>
  </body>
</html>